# Generated by Django 4.0.5 on 2022-06-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='description',
        ),
    ]
